package com.vitea.domain;

import java.util.Date;
/**
 * API user
 * @author liushahe
 *
 */
public class ApiUser {


    private String type;

   /**
    * 开放用户编号
    */
    private String appid;

   /**
    * 开放用户密码
    */
    private String appsecret;

   /**
    * 白名单
    */
    private String whitelist;

   /**
    * 名称
    */
    private String name;

   /**
    * 描述
    */
    private String description;

   /**
    * 注册时间
    */
    private Date time;

    
   

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QK_API_USER.TYPE
     *
     * @return the value of QK_API_USER.TYPE
     *
     * @mbg.generated Mon Jul 23 16:24:28 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QK_API_USER.TYPE
     *
     * @param type the value for QK_API_USER.TYPE
     *
     * @mbg.generated Mon Jul 23 16:24:28 CST 2018
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QK_API_USER.APPID
     *
     * @return the value of QK_API_USER.APPID
     *
     * @mbg.generated Mon Jul 23 16:24:28 CST 2018
     */
    public String getAppid() {
        return appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QK_API_USER.APPID
     *
     * @param appid the value for QK_API_USER.APPID
     *
     * @mbg.generated Mon Jul 23 16:24:28 CST 2018
     */
    public void setAppid(String appid) {
        this.appid = appid == null ? null : appid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QK_API_USER.APPSECRET
     *
     * @return the value of QK_API_USER.APPSECRET
     *
     * @mbg.generated Mon Jul 23 16:24:28 CST 2018
     */
    public String getAppsecret() {
        return appsecret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QK_API_USER.APPSECRET
     *
     * @param appsecret the value for QK_API_USER.APPSECRET
     *
     * @mbg.generated Mon Jul 23 16:24:28 CST 2018
     */
    public void setAppsecret(String appsecret) {
        this.appsecret = appsecret == null ? null : appsecret.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QK_API_USER.WHITELIST
     *
     * @return the value of QK_API_USER.WHITELIST
     *
     * @mbg.generated Mon Jul 23 16:24:28 CST 2018
     */
    public String getWhitelist() {
        return whitelist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QK_API_USER.WHITELIST
     *
     * @param whitelist the value for QK_API_USER.WHITELIST
     *
     * @mbg.generated Mon Jul 23 16:24:28 CST 2018
     */
    public void setWhitelist(String whitelist) {
        this.whitelist = whitelist == null ? null : whitelist.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QK_API_USER.NAME
     *
     * @return the value of QK_API_USER.NAME
     *
     * @mbg.generated Mon Jul 23 16:24:28 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QK_API_USER.NAME
     *
     * @param name the value for QK_API_USER.NAME
     *
     * @mbg.generated Mon Jul 23 16:24:28 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QK_API_USER.DESCRIPTION
     *
     * @return the value of QK_API_USER.DESCRIPTION
     *
     * @mbg.generated Mon Jul 23 16:24:28 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QK_API_USER.DESCRIPTION
     *
     * @param description the value for QK_API_USER.DESCRIPTION
     *
     * @mbg.generated Mon Jul 23 16:24:28 CST 2018
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QK_API_USER.TIME
     *
     * @return the value of QK_API_USER.TIME
     *
     * @mbg.generated Mon Jul 23 16:24:28 CST 2018
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QK_API_USER.TIME
     *
     * @param time the value for QK_API_USER.TIME
     *
     * @mbg.generated Mon Jul 23 16:24:28 CST 2018
     */
    public void setTime(Date time) {
        this.time = time;
    }
}